name: CI

# On every pull request, but only on push to main
on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run pre-commit
        run: |
          python -m pip install pre-commit
          pre-commit run --all-files
